### ISSUE TITLE
Investigate spatial workflow result plotting

### ISSUE THREAD

**Issue by BryanRumsey** [StochSS/stochss#1424]
Single trajectory results display properly, however multi trajectory results produce the following error:

## Error
```
[E 21:06:53 StochSS stochss_errors.py:56] Exception information: {'Reason': 'Uncaught Critical Error', 'Message': "'list' object has no attribute 'plot_property'"}
    Traceback (most recent call last):
      File "/stochss/stochss/handlers/workflows.py", line 256, in get
        fig = job.get_plot_from_spatial_results(
      File "/stochss/stochss/handlers/util/stochss_job.py", line 521, in get_plot_from_spatial_results
        fig = result.plot_property(
    AttributeError: 'list' object has no attribute 'plot_property'
```

**Comment by BryanRumsey** [comment]
This issue has a corresponding issue in SpatialPy [#348](https://github.com/StochSS/SpatialPy/issues/348)
