### ISSUE TITLE
Unpickling of a spatial result fails

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#307]
To reproduce, download a spatial result and then try to unpickle it. Here is my result. 

150303_194534/results/result0 
Traceback (most recent call last):
  File "./spatial2xdmf.py", line 15, in <module>
    result = pickle.load(fh)
  File "/Library/Python/2.7/site-packages/dill/dill.py", line 150, in load
    obj = pik.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1217, in load_build
    setstate(state)
  File "/Users/andreash/github/ahellander/pyurdme/pyurdme/pyurdme.py", line 150, in __setstate__
    raise Exception("Error unpickling model, could not recreate the subdomain functions"+str(e))
Exception: Error unpickling model, could not recreate the subdomain functionsin method 'new_MeshFunctionSizet', argument 1 of type 'dolfin::MeshFunction< std::size_t > const &'

**Comment by ahellander** [comment]
This was actually not true, but the bundled pyurdme has to be used, for some reason.

/Andreas
-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Mar 9, 2015, at 6:52 PM, bbbales2 <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #307<https://github.com/StochSS/stochss/issues/307>.

**Comment by ahellander** [comment]
This was actually not true, but the bundled pyurdme has to be used, for some reason. 

/Andreas 
-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University
