### ISSUE TITLE
Models with non-SSA 'custom mass action' reactions fail to covert, and do not show error

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#346]
3 places:
1. run deterministic + sensitivity job
2. run of parameter estimation
3. Export of zip

need to catch the exception and report and error to the user.  This is already done for run stochastic and deterministic jobs.

**Comment by briandrawert** [comment]
ERROR    2015-04-23 18:06:37,218 wsgi.py:278] 
Traceback (most recent call last):
  File "/Users/bdaigle/TEMP/stochss/sdk/python/google/appengine/runtime/wsgi.py", line 266, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/Users/bdaigle/TEMP/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 1519, in __call__
    response = self._internal_error(e)
  File "/Users/bdaigle/TEMP/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/bdaigle/TEMP/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/bdaigle/TEMP/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Users/bdaigle/TEMP/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/Users/bdaigle/TEMP/stochss/app/stochssapp.py", line 175, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/Users/bdaigle/TEMP/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Users/bdaigle/TEMP/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/Users/bdaigle/TEMP/stochss/app/handlers/modeleditor.py", line 612, in get
    szip.addStochKitModel(model)
  File "/Users/bdaigle/TEMP/stochss/app/handlers/exportimport.py", line 141, in addStochKitModel
    jsonModel["model"] = self.addBytes('models/data/{0}.xml'.format(model.name), model.createStochKitModel().serialize())
  File "/Users/bdaigle/TEMP/stochss/app/handlers/modeleditor.py", line 82, in createStochKitModel
    sModel.addReaction(stochss.model.Reaction(reaction['name'], reactants, products, None, True, sModel.getParameter(reaction['rate']), None))
  File "/Users/bdaigle/TEMP/stochss/app/stochss/model.py", line 284, in __init__
    self.createMassAction()
  File "/Users/bdaigle/TEMP/stochss/app/stochss/model.py", line 301, in createMassAction
    raise ReactionError("Reaction: A mass-action reaction cannot involve more than two of one species or one of two species.")
ReactionError: Reaction: A mass-action reaction cannot involve more than two of one species or one of two species.

**Comment by briandrawert** [comment]
Fixed in https://github.com/StochSS/stochss/pull/352
