### ISSUE TITLE
Check that deleting a mesh is possible (in any case)

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#347]

**Comment by briandrawert** [comment]
Not sure if this is related, also getting this error intermittently in the logs:
```
INFO     2015-04-23 19:19:32,804 module.py:643] default: "GET /meshes/threeJsMesh/6473924464345088 HTTP/1.1" 200 547779
INFO     2015-04-23 19:19:32,810 module.py:643] default: "PUT /models/6051711999279104 HTTP/1.1" 200 470
INFO     2015-04-23 19:19:42,118 module.py:643] default: "DELETE /models/6051711999279104 HTTP/1.1" 200 2
ERROR    2015-04-23 19:19:44,444 webapp2.py:1528] 'mesh_wrapper_id'
Traceback (most recent call last):
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/Users/brian/Desktop/research/stochss.develop/app/stochssapp.py", line 175, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/Users/brian/Desktop/research/stochss.develop/app/handlers/modeleditor.py", line 439, in post
    modelId = ModelManager.updateModel(self, jsonModel)
  File "/Users/brian/Desktop/research/stochss.develop/app/handlers/modeleditor.py", line 361, in updateModel
    meshDbCurrent = mesheditor.MeshWrapper.get_by_id(modelWrap.spatial["mesh_wrapper_id"])
KeyError: 'mesh_wrapper_id'
ERROR    2015-04-23 19:19:44,447 wsgi.py:278]
Traceback (most recent call last):
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/google/appengine/runtime/wsgi.py", line 266, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1519, in __call__
    response = self._internal_error(e)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/Users/brian/Desktop/research/stochss.develop/app/stochssapp.py", line 175, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
INFO     2015-04-23 19:19:44,455 module.py:643] default: "POST /models HTTP/1.1" 500 -
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/Users/brian/Desktop/research/stochss.develop/app/handlers/modeleditor.py", line 439, in post
    modelId = ModelManager.updateModel(self, jsonModel)
  File "/Users/brian/Desktop/research/stochss.develop/app/handlers/modeleditor.py", line 361, in updateModel
    meshDbCurrent = mesheditor.MeshWrapper.get_by_id(modelWrap.spatial["mesh_wrapper_id"])
KeyError: 'mesh_wrapper_id'
INFO     2015-04-23 19:19:44,682 module.py:643] default: "GET /meshes/threeJsMesh/6473924464345088 HTTP/1.1" 200 547779
```

**Comment by briandrawert** [comment]
Confirmed, you can delete meshes that are imported from the outside.  A mesh from the public library can not be deleted.  That is now issue #350
