### ISSUE TITLE
Error importing a backup file 

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#349]
(stefan) I get the error below when I try to import a backup and overwrite existing data. I’ve attached the ZIP-file.

```
Traceback (most recent call last):
  File "/home/stefan/Projects/stochss_testing/stochss/sdk/python/google/appengine/runtime/wsgi.py", line 266, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/home/stefan/Projects/stochss_testing/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 1519, in __call__
    response = self._internal_error(e)
  File "/home/stefan/Projects/stochss_testing/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/home/stefan/Projects/stochss_testing/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/home/stefan/Projects/stochss_testing/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/home/stefan/Projects/stochss_testing/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/home/stefan/Projects/stochss_testing/stochss/app/stochssapp.py", line 175, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/home/stefan/Projects/stochss_testing/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/home/stefan/Projects/stochss_testing/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/home/stefan/Projects/stochss_testing/stochss/app/handlers/exportimport.py", line 1300, in post
    otherJob.delete()
  File "/home/stefan/Projects/stochss_testing/stochss/app/handlers/spatial.py", line 73, in delete
    if os.path.exists(str(output_path)+self.uuid):
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by briandrawert** [comment]
Broken backup file is here: http://hydra.cs.ucsb.edu/stochss/issue_349/backup_5dmSWj.zip

**Comment by briandrawert** [comment]
I did this with a clean StochSS, import worked correctly.  When I do it the 2nd time, it give me the error.

**Comment by briandrawert** [comment]
Fixed in https://github.com/StochSS/stochss/pull/352
