### ISSUE TITLE
FlexCloud: Parameter Estimation page fails to load fails intermittently

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#432]
```
ERROR    2015-06-08 20:04:22,849 wsgi.py:278] 
Traceback (most recent call last):
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/google/appengine/runtime/wsgi.py", line 266, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1519, in __call__
    response = self._internal_error(e)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/Users/brian/Desktop/research/stochss.develop/app/stochssapp.py", line 276, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/Users/brian/Desktop/research/stochss.develop/app/handlers/stochoptim.py", line 696, in get
    job_status = task_status[optimization.cloudDatabaseID]
KeyError: u'a7743ba4-d0ea-414f-850b-062c0e5854f7'
```

**Comment by dnath** [comment]
fixed in 5c54f0f9a5f1dd3dd44c5f5ee1d611b43ff2a8b7

**Comment by briandrawert** [comment]
A similar issue happened when I submitted a deterministic job:
```
ERROR    2015-06-10 18:03:17,162 wsgi.py:278] 
Traceback (most recent call last):
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/google/appengine/runtime/wsgi.py", line 266, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1519, in __call__
    response = self._internal_error(e)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/Users/brian/Desktop/research/stochss.develop/app/stochssapp.py", line 295, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/Users/brian/Desktop/research/stochss.develop/app/handlers/status.py", line 36, in get
    context = self.getContext()
  File "/Users/brian/Desktop/research/stochss.develop/app/handlers/status.py", line 445, in getContext
    job_status = task_status[job.cloudDatabaseID]
KeyError: u'a7743ba4-d0ea-414f-850b-062c0e5854f7'
```

**Comment by briandrawert** [comment]
Above error was addressed in https://github.com/StochSS/stochss/pull/453

**Comment by briandrawert** [comment]
Needs to be checked
