### ISSUE TITLE
Strange errors on launch

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#526]
I just got a bunch of errors on launch that looked like:

"Traceback (most recent call last):
  File "/home/bbales2/stochss/sdk/python/google/appengine/runtime/wsgi.py", line 239, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/home/bbales2/stochss/sdk/python/google/appengine/runtime/wsgi.py", line 298, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/home/bbales2/stochss/sdk/python/google/appengine/runtime/wsgi.py", line 84, in LoadObject
    obj = __import__(path[0])
  File "/home/bbales2/stochss/app/stochssapp.py", line 28, in <module>
    from backend.backendservice import backendservices  #from backend.backendservice import *
  File "/home/bbales2/stochss/app/backend/backendservice.py", line 6, in <module>
    from infrastructure_manager import InfrastructureManager
  File "/home/bbales2/stochss/app/backend/infrastructure_manager.py", line 8, in <module>
    import backend_handler
  File "/home/bbales2/stochss/app/backend/backend_handler.py", line 38, in <module>
    BACKEND_URL = 'http://%s' % modules.get_hostname(BACKEND_NAME)
  File "/home/bbales2/stochss/sdk/python/google/appengine/api/modules/modules.py", line 458, in get_hostname
    _ResultHook).get_result()
  File "/home/bbales2/stochss/sdk/python/google/appengine/api/apiproxy_stub_map.py", line 612, in get_result
    return self.__get_result_hook(self)
INFO     2015-09-22 21:08:42,313 module.py:643] default: "GET /login HTTP/1.1" 500 -
  File "/home/bbales2/stochss/sdk/python/google/appengine/api/modules/modules.py", line 441, in _ResultHook
    _CheckAsyncResult(rpc, mapped_errors, [])
  File "/home/bbales2/stochss/sdk/python/google/appengine/api/modules/modules.py", line 146, in _CheckAsyncResult
    raise mapped_error()
InvalidModuleError"

This was after doing ./run.ubuntu.sh but before the server launched. However, they went away and eventually the server launched (at try 8). Usually it's up at like try 3 on my computer.

This is in the molnsconfig branch, so maybe it's just there and they go away once we fix things up, but it was weird.

Ben

**Comment by briandrawert** [comment]
I had this same error as well.  However, it was not repeatable.

**Comment by bbbales2** [comment]
It's old enough and I've gone long enough without seeing it that I'm fine closing this.

**Comment by briandrawert** [comment]
Sounds good to me
