### ISSUE TITLE
Spatial jobs not working in the cloud

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#587]
I run cylinder_demo or the Hes1 model and get this error when I try to view the results:

```
Traceback (most recent call last):
  File "/home/bbales2/stochss/app/handlers/spatial.py", line 120, in get
    job.preprocess(trajectory)
  File "/home/bbales2/stochss/app/db_models/spatial_job.py", line 47, in preprocess
    with open(str(self.outData + '/results/result{0}'.format(trajectory))) as fd:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

```

(The error is correctly  propagated to the UI -- but there shouldn't be an error)

**Comment by briandrawert** [comment]
Fixed in eb5ec9adf8605619634bb66b61dc573438f92ab3
